version: '3'

services:
  apisix:
    image: apache/apisix:3.2.1-debian
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    environment:
      - APISIX_STAND_ALONE=true
    ports:
      - "9080:9080"
    
  wrk-apisix:
    image: williamyeh/wrk
    command: -t2 -c400 -d30s http://apisix:9080/foo/bar
    depends_on:
      - apisix