version: '3'

services:
  apisix:
    image: apache/apisix:3.10.0-debian
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    environment:
      - APISIX_STAND_ALONE=true
    expose:
      - 9080
    user: "${UID}:${GID}"
    
  wrk:
    image: williamyeh/wrk
    command: -t2 -c400 -d5m http://apisix:9080/foo/bar
    depends_on:
      - apisix